spring:
  datasource:
    url: jdbc:mysql://140.143.234.59:3406/mtnj?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: dev
    password: lzyDDX123$%^789
swagger:
  enable: true