server:
  port: 8081
spring:
  profiles:
    active: $[build.profile]
  datasource:
    url: $[spring.datasource.url]
    username: $[spring.datasource.username]
    password: $[spring.datasource.password]
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 20
      max-wait: 10000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 600000
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
mapper:
  not-empty: true
  identity: MYSQL
  style: normal
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.lzy.mtnj.mapper: debug
swagger:
  enable: $[swagger.enable]